server:
  port: 9013
  servlet:
    # 设置响应的字符编码，避免流式响应返回乱码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: langchain4j-13chat-rag01
  ai:
    alibaba:
      apiKey: ${DASHSCOPE_API_KEY}
      baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1
      qwenPlusModelName: qwen-plus

# 向量数据库配置
vector:
  qdrant:
    host: 127.0.0.1
    port: 6334
    collectionName: test-rag