server:
  port: 9004
spring:
  application:
    name: langchain4j-04low-high-api
  ai:
    alibaba:
      qwen:
        apiKey: ${DASHSCOPE_API_KEY}
        modelName: qwen-plus
        baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1
    deepseek:
      apiKey: ${DEEPSEEK_API_KEY}
      modelName: deepseek-chat
      baseUrl: https://api.deepseek.com/v1