server:
  port: 9007
  servlet:
    # 设置响应的字符编码，避免流式响应返回乱码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: langchain4j-07chat-stream
  ai:
    alibaba:
      apiKey: ${DASHSCOPE_API_KEY}
      baseUrl: https://dashscope.aliyuncs.com/compatible-mode/v1
      qwenModelName: qwen-plus